spring:
  application:
    name: redis-performance
  r2dbc:
    url: r2dbc:mysql://localhost:3306/performance?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: io.r2dbc.mysql.MySqlConnectionFactoryProvider